build:
	which sed
	sed --version
	printf '%s\n' 's/\\/\\\\/g'
	echo 1 | 'C:\Program Files\Git\usr\bin\sed.exe' --debug -e s/\\\\/\\\\\\\\/g
	echo 1 | 'C:\Program Files\Git\usr\bin\sed.exe' --debug -e 's/\\/\\\\/g'
