#!/usr/bin/env python

import os
import sys
import sysconfig

from Cython.Build import cythonize
from setuptools import setup
from setuptools.command.build_ext import build_ext
from setuptools.extension import Extension


def _read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()


class jq_with_deps_build_ext(build_ext):
    def finalize_options(self):
        build_ext.finalize_options(self)

    def get_libraries(self, ext: Extension) -> list[str]:
        # When using non-MSVC compilers on Windows, the Python lib to link
        # against generated by setuptools fails to add the "t" suffix for
        # free-threaded builds. We therefore override `get_libraries` to
        # work around this.
        #
        # See: https://github.com/pypa/setuptools/issues/5126
        if os.name == "nt" and sysconfig.get_config_var("Py_GIL_DISABLED"):
            pythonlib = "python%d%dt" % (
                sys.hexversion >> 24,
                (sys.hexversion >> 16) & 0xFF,
            )
            if self.debug:
                pythonlib += '_d'
            return ext.libraries + [pythonlib]
        else:
            return build_ext.get_libraries(self, ext)


jq_extension = Extension(
    "jq",
    sources=["jq.pyx"],
    # MS_WIN64 has to be set to successfully build when using MinGW for 64-bit
    # Windows. See: https://github.com/cython/cython/issues/2670
    define_macros=[("MS_WIN64" , 1)] if os.name == "nt" and sys.maxsize > 2**32  else None,
    extra_link_args=["-lm"] + (["-Wl,-Bstatic", "-lpthread", "-lshlwapi", "-static-libgcc"] if os.name == 'nt' else [])
)

setup(
    name='jq',
    version='1.10.2',
    description='jq is a lightweight and flexible JSON processor.',
    long_description=_read("README.rst"),
    author='Michael Williamson',
    url='https://github.com/mwilliamson/jq.py',
    python_requires='>=3.8',
    license='BSD 2-Clause',
    ext_modules = cythonize([jq_extension]),
    cmdclass={"build_ext": jq_with_deps_build_ext},
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Programming Language :: Python :: 3.14',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Programming Language :: Python :: Implementation :: CPython',
    ],
)

