name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    name: Build cp310-win_amd64 wheel

    needs: build_wheels_matrix

    runs-on: windows-2022

    steps:

    - name: Check whether to build wheel
      id: should-build-wheel
      shell: bash
      run: echo true=1 >> $GITHUB_OUTPUT

    - uses: actions/checkout@v7
      if: steps.should-build-wheel.outputs.true

    - name: Set up MSYS2
      if: steps.should-build-wheel.outputs.true && runner.os == 'Windows'
      uses: ./.github/actions/setup-msys2
      with:
        arch: AMD64

    - name: Set up QEMU
      if: steps.should-build-wheel.outputs.true && runner.os == 'Linux'
      uses: docker/setup-qemu-action@v4
      with:
        platforms: all

    - name: Build wheels
      if: steps.should-build-wheel.outputs.true
      uses: pypa/cibuildwheel@v3.3.0
      with:
        only: cp310-win_amd64

    - uses: actions/upload-artifact@v7
      if: steps.should-build-wheel.outputs.true
      with:
        name: dist-wheel-cp310-win_amd64
        path: ./wheelhouse/*.whl
